Sync up GitHub actions with 'graphql-js'

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,14 +26,34 @@ jobs:
       - name: Install Dependencies
         run: npm ci
 
-      - name: Lint Prettier
-        run: npm run prettier:check
-
       - name: Lint ESLint
         run: npm run lint
 
       - name: Lint Flow
         run: npm run check
+
+      - name: Lint Prettier
+        run: npm run prettier:check
+
+      - name: Spellcheck
+        run: npm run check:spelling
+
+  checkForCommonlyIgnoredFiles:
+    name: Check for commonly ignored files
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v2
+
+      - name: Check if commit contains files that should be ignored
+        run: |
+          git clone --depth 1 https://github.com/github/gitignore.git &&
+          cat gitignore/Node.gitignore $(find gitignore/Global -name "*.gitignore" | grep -v ModelSim) > all.gitignore &&
+          if  [[ "$(git ls-files -iX all.gitignore)" != "" ]]; then
+            echo "::error::Please remove these files:"
+            git ls-files -iX all.gitignore
+            exit 1
+          fi
 
   integrationTests:
     name: Run integration tests
@@ -119,20 +139,3 @@ jobs:
 
       - name: Run Tests
         run: npm run testonly
-
-  checkForCommonlyIgnoredFiles:
-    name: Check for commonly ignored files
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v2
-
-      - name: Check if commit contains files that should be ignored
-        run: |
-          git clone --depth 1 https://github.com/github/gitignore.git &&
-          cat gitignore/Node.gitignore $(find gitignore/Global -name "*.gitignore" | grep -v ModelSim) > all.gitignore &&
-          if  [[ "$(git ls-files -iX all.gitignore)" != "" ]]; then
-            echo "::error::Please remove these files:"
-            git ls-files -iX all.gitignore
-            exit 1
-          fi
